import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export interface PDFExportOptions {
  filename?: string;
  title?: string;
  author?: string;
  includeMetadata?: boolean;
}

/**
 * Export HTML content to PDF
 * @param element - The HTML element to export
 * @param options - Export options
 */
export async function exportToPDF(
  element: HTMLElement,
  options: PDFExportOptions = {}
): Promise<void> {
  try {
    const {
      filename = 'document.pdf',
      title = 'Document',
      author = '',
      includeMetadata = true,
    } = options;

    // Create canvas from HTML element
    const canvas = await html2canvas(element, {
      scale: 2, // Higher quality
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff',
    });

    const imgData = canvas.toDataURL('image/png');
    const imgWidth = 210; // A4 width in mm
    const pageHeight = 297; // A4 height in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;

    // Initialize PDF
    const pdf = new jsPDF('p', 'mm', 'a4');
    let position = 0;

    // Add metadata
    if (includeMetadata) {
      pdf.setProperties({
        title: title,
        author: author,
        subject: title,
        creator: 'CLM Platform',
      });
    }

    // Add first page
    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    // Add additional pages if content is longer than one page
    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    // Save PDF
    pdf.save(filename);
  } catch (error) {
    console.error('Error exporting to PDF:', error);
    throw new Error('Failed to export PDF');
  }
}

/**
 * Export proposal content to PDF
 * @param proposalTitle - The title of the proposal
 * @param proposalContent - The HTML content of the proposal
 * @param metadata - Additional metadata
 */
export async function exportProposalToPDF(
  proposalTitle: string,
  proposalContent: string,
  metadata?: {
    author?: string;
    status?: string;
    createdDate?: string;
    version?: number;
  }
): Promise<void> {
  // Create a temporary container
  const container = document.createElement('div');
  container.style.position = 'absolute';
  container.style.left = '-9999px';
  container.style.width = '210mm'; // A4 width
  container.style.padding = '20mm';
  container.style.backgroundColor = '#ffffff';
  container.style.fontFamily = 'Arial, sans-serif';

  // Add header
  const header = document.createElement('div');
  header.style.marginBottom = '20px';
  header.style.borderBottom = '2px solid #333';
  header.style.paddingBottom = '10px';

  const titleEl = document.createElement('h1');
  titleEl.textContent = proposalTitle;
  titleEl.style.fontSize = '24px';
  titleEl.style.marginBottom = '10px';
  titleEl.style.color = '#333';
  header.appendChild(titleEl);

  if (metadata) {
    const metadataEl = document.createElement('div');
    metadataEl.style.fontSize = '12px';
    metadataEl.style.color = '#666';

    const metadataText: string[] = [];
    if (metadata.author) metadataText.push(`Author: ${metadata.author}`);
    if (metadata.status) metadataText.push(`Status: ${metadata.status}`);
    if (metadata.version) metadataText.push(`Version: ${metadata.version}`);
    if (metadata.createdDate) metadataText.push(`Date: ${metadata.createdDate}`);

    metadataEl.textContent = metadataText.join(' | ');
    header.appendChild(metadataEl);
  }

  container.appendChild(header);

  // Add content
  const contentEl = document.createElement('div');
  contentEl.innerHTML = proposalContent;
  contentEl.style.fontSize = '14px';
  contentEl.style.lineHeight = '1.6';
  contentEl.style.color = '#333';
  container.appendChild(contentEl);

  // Add footer
  const footer = document.createElement('div');
  footer.style.marginTop = '30px';
  footer.style.paddingTop = '10px';
  footer.style.borderTop = '1px solid #ccc';
  footer.style.fontSize = '10px';
  footer.style.color = '#999';
  footer.style.textAlign = 'center';
  footer.textContent = `Generated by CLM Platform on ${new Date().toLocaleDateString()}`;
  container.appendChild(footer);

  // Append to document
  document.body.appendChild(container);

  try {
    // Export to PDF
    await exportToPDF(container, {
      filename: `${proposalTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`,
      title: proposalTitle,
      author: metadata?.author || '',
    });
  } finally {
    // Clean up
    document.body.removeChild(container);
  }
}

/**
 * Export contract to PDF with signature placeholders
 */
export async function exportContractToPDF(
  contractTitle: string,
  contractContent: string,
  signers: { name: string; email: string; signed: boolean }[] = [],
  metadata?: any
): Promise<void> {
  // Similar to proposal export but with signature section
  const container = document.createElement('div');
  container.style.position = 'absolute';
  container.style.left = '-9999px';
  container.style.width = '210mm';
  container.style.padding = '20mm';
  container.style.backgroundColor = '#ffffff';
  container.style.fontFamily = 'Arial, sans-serif';

  // Add header
  const header = document.createElement('div');
  header.style.marginBottom = '20px';
  header.style.borderBottom = '2px solid #333';
  header.style.paddingBottom = '10px';

  const titleEl = document.createElement('h1');
  titleEl.textContent = contractTitle;
  titleEl.style.fontSize = '24px';
  titleEl.style.marginBottom = '10px';
  header.appendChild(titleEl);

  container.appendChild(header);

  // Add content
  const contentEl = document.createElement('div');
  contentEl.innerHTML = contractContent;
  contentEl.style.fontSize = '14px';
  contentEl.style.lineHeight = '1.6';
  container.appendChild(contentEl);

  // Add signature section
  if (signers.length > 0) {
    const signaturesEl = document.createElement('div');
    signaturesEl.style.marginTop = '40px';
    signaturesEl.style.pageBreakInside = 'avoid';

    const signaturesTitle = document.createElement('h2');
    signaturesTitle.textContent = 'Signatures';
    signaturesTitle.style.fontSize = '18px';
    signaturesTitle.style.marginBottom = '20px';
    signaturesEl.appendChild(signaturesTitle);

    signers.forEach((signer) => {
      const signerBlock = document.createElement('div');
      signerBlock.style.marginBottom = '30px';

      const signerName = document.createElement('div');
      signerName.textContent = signer.name;
      signerName.style.fontSize = '14px';
      signerName.style.fontWeight = 'bold';
      signerBlock.appendChild(signerName);

      const signerEmail = document.createElement('div');
      signerEmail.textContent = signer.email;
      signerEmail.style.fontSize = '12px';
      signerEmail.style.color = '#666';
      signerBlock.appendChild(signerEmail);

      const signatureLine = document.createElement('div');
      signatureLine.style.marginTop = '10px';
      signatureLine.style.borderBottom = '1px solid #000';
      signatureLine.style.width = '200px';
      signatureLine.style.height = '50px';
      signerBlock.appendChild(signatureLine);

      const status = document.createElement('div');
      status.textContent = signer.signed ? '✓ Signed' : 'Pending';
      status.style.fontSize = '12px';
      status.style.color = signer.signed ? '#059669' : '#6b7280';
      status.style.marginTop = '5px';
      signerBlock.appendChild(status);

      signaturesEl.appendChild(signerBlock);
    });

    container.appendChild(signaturesEl);
  }

  document.body.appendChild(container);

  try {
    await exportToPDF(container, {
      filename: `${contractTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`,
      title: contractTitle,
    });
  } finally {
    document.body.removeChild(container);
  }
}
